platform :ios, '15.0'
use_frameworks!

target 'DSKings_Example' do
    pod 'DSKings', :path => '../'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '5.7'
       
            next unless config.name == 'Debug'
            config.build_settings['LD_RUNPATH_SEARCH_PATHS'] = [
                '$(FRAMEWORK_SEARCH_PATHS)'
            ]
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
            config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        end
    end

    installer.pods_project.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
end
